/*
 Copyright 2013 ClinRisk Ltd.
 Modifications to port QRISK2-2014 to javascript copyright 2014 Black Pear Software Ltd.

 This file is part of QRISK2-2014 (http://qrisk.org, original sources at http://svn.clinrisk.co.uk/opensource/qrisk2).

 QRISK2-2014 is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 QRISK2-2014 is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with QRISK2-2014.  If not, see <http://www.gnu.org/licenses/>.

 Additional terms

 The following disclaimer must be held together with any risk score score generated by this code.  If the score is displayed, then this disclaimer must be displayed or otherwise be made easily accessible, e.g. by a prominent link alongside it.
 The initial version of this file, to be found at http://svn.clinrisk.co.uk/opensource/qrisk2, faithfully implements QRISK2-2014.
 ClinRisk Ltd. have released this code under the GNU Lesser General Public License to enable others to implement the algorithm faithfully.
 However, the nature of the GNU Lesser General Public License is such that we cannot prevent, for example, someone accidentally
 altering the coefficients, getting the inputs wrong, or just poor programming.
 ClinRisk Ltd. stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same results as the original code posted at http://svn.clinrisk.co.uk/opensource/qrisk2.
 Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.

 End of additional terms
 */

module.exports = ['age', 'b_AF', 'b_ra', 'b_renal', 'b_treatedhyp', 'b_type1', 'b_type2', 'bmi', 'ethrisk', 'fh_cvd', 'rati', 'sbp', 'smoke_cat', 'surv', 'town'];